services:
  postgres:
    image: postgres:17
    container_name: book-postgres
    restart: always
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passPost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: book-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    image: ghcr.io/avishkar74/book:43a4fb4
    container_name: book-app
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: passPost

volumes:
  postgres_data:
