spring:
  application:
    name: libraryManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: postgres
    password: passPost

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:


server:
  port: 8080

logging:
  level:
    root: INFO
    com.Avishkar: DEBUG
